### ISSUE TITLE
Locale

### ISSUE THREAD

**Issue by jeffreykegler** [rns/kollos-luif-doc#8]
Reading the Lua 5.1 manual, I see that it supports locales.  I think we want to not support this in the LUIF -- that is, have Lua run as if run with LC_ALL=C, or its equivalent.

The reference manual should state this somewhere.

**Comment by rns** [comment]
To be more specific, Lua has `os.setlocale(locale  [, category]))` [1], so we can say that 
1. LUIF is locale-agnostic; or 
2. LUIF runs in 'C locale' or 'implementation-defined native locale' per Lua manual [1] and then probably will need to call `os.setlocale('C')` or `os.setlocale(nil)` to enforce the locale if/when required; or
3. say nothing for now until we're sure?

[1]

> If locale is the empty string, the current locale is set to an implementation-defined native locale. If locale is the string "C", the current locale is set to the standard C locale.
> — http://www.lua.org/manual/5.1/manual.html#pdf-os.setlocale

**Comment by jeffreykegler** [comment]
Looking more into this, Lua seems to rely on the C library to do almost all of the work.  Sorting is the trickiest thing.  Maybe for now, merely say that full support is only assured for the "C" locale  -- support for others may be limited, inconsistent, or removed in the future.

In particular, we may want to note that `os.setlocale()` for anything but the `"C"` locale may fail, silently or otherwise.

**Comment by rns** [comment]
Locale support section added in a964224 and 4fdd29f.
