### ISSUE TITLE
grammar for luif_self:rule_from_string() and luif_self:rule_parse() 

### ISSUE THREAD

**Issue by rns** [rns/kollos-luif-doc#9]
`luif_self:rule_from_string()` and `luif_self:rule_parse()` mentioned in internals.md, have no grammar argument -- the intent is that (1) there will always have one default grammar in KHIL or (2) `luif_self` is just a placeholder meaning "the current grammar object"?

**Comment by jeffreykegler** [comment]
Good catch in the case of `luif_self:rule_parse` -- we need an option to set the grammar, and probably a default.

With `luif_self:rule_from_string()`, the defaults I talking about in #10 would apply.

**Comment by rns** [comment]
Can we update post-processing in `manual.md` and internals/KIR in `etc` introducing D2L and requiring that D2L should compile LUIF's BNF statements into KIR?

**Comment by rns** [comment]
D2L introduced in 0c47da0.

**Comment by jeffreykegler** [comment]
The changes look good.

**Comment by rns** [comment]
Great, I'll introduce a grammar start rule per my suggestion https://github.com/rns/kollos-luif-doc/issues/10#issuecomment-98696337 and your writeup https://github.com/rns/kollos-luif-doc/pull/28.

**Comment by rns** [comment]
D2L and start rule https://github.com/rns/kollos-luif-doc/issues/10#issuecomment-101731207 seem to address this. Can it be closed?

**Comment by jeffreykegler** [comment]
I have further questions & thoughts -- in particular the current writeup
makes `start` a reserved symbol -- I'm not sure I don't prefer an adverb.
 (Most grammars I expect won't specify a start explicitly, but will let it
be the first rule by default.)  But our discussion will be on-going, and we
can close this if you like.

**Comment by rns** [comment]
Great, so let's discuss start rule in #10.
